### ISSUE TITLE
i cant convert and import beatmaps

### ISSUE THREAD

**Issue by echofallenn** [ojh050118/Circle#157]
all the folders are just blank, even in the C:/Program Files (x86)/ Steam/common/workshop/(idk the adofai id)/the workshop item
idk what to do.

**Comment by ojh050118** [comment]
@echofallenn First of all, thank you for your interest in Circle.

https://github.com/ojh050118/Circle/assets/51792037/5a85d4ed-ff21-4d1a-9dcd-8b13090e2306

I confirmed that it works well in my environment. Please check if it is the correct path.
If it still doesn't work, please provide detailed information, including version, logs, and videos. I will help you as much as I can.

**Comment by echofallenn** [comment]
ok! ima try it.
